# Generated by Django 5.0.6 on 2024-05-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=200)),
                ('con_password', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
            ],
        ),
    ]
