# Generated by Django 5.0.6 on 2024-05-27 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_logintable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Rescheduled', 'Rescheduled'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.logintable')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.patient')),
            ],
        ),
    ]
